import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Balance, SidebarAdmin } from "@/components";
import { ThemeProvider } from "@/components/shared/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <SidebarAdmin />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
            <main className="flex w-full justify-center min-h-[calc(100vh-7rem)] p-8">
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
              <Balance />
            </main>
          </div>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
